name: Compile and Publish Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PAGES_BRANCH: 'gh-pages'
  PAGES_DIRECTORY: 'charts'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Create charts directory
        run: |
          mkdir -p $PAGES_DIRECTORY

      - name: Lint and package Helm charts
        run: |
          for dir in $(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path '.' -not -name '$PAGES_DIRECTORY'); do
            if [ -f "$dir/Chart.yaml" ]; then
              echo "Packaging chart in $dir"
              helm lint "$dir"
              helm package "$dir" --destination "$PAGES_DIRECTORY"
            fi
          done

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $PAGES_DIRECTORY
          publish_branch: $PAGES_BRANCH

